### ISSUE TITLE
Купленная недвижимость

### ISSUE THREAD

**Issue by denyszamiatin** [denyszamiatin/Monopoly2#13]
При попадании игрока на клетку с купленной недвижимостью необходимо снять соответствующую сумму со счета игрока и перевести ее владельцу недвижимости

**Comment by YuriyLyashko** [comment]
Пропоную переформатувати початковий вигляд констанни _FIELDS. Як варіант: [[{'field_name': 'Baltic Avenue', 'cost': 60, 'pay': 10, 'owner': '', ...}]]
